export const categoryList = [
    {
        icon:'https://www.shutterstock.com/image-photo/assortment-healthy-foods-on-white-260nw-2693074295.jpg',
        label:'Food',
        subCategories:[
            {
                subIcon:'https://static.vecteezy.com/system/resources/thumbnails/044/812/130/small/stacked-fertilizer-bags-for-enhanced-plant-growth-isolated-on-transparent-background-png.png',
                subLabel:'Grains'
            },
            {
                subIcon:'https://png.pngtree.com/png-vector/20240524/ourmid/pngtree-beautiful-mix-fruits-composition-png-image_12511891.png',
                subLabel:'Fruits'
            },
            {
                subIcon:'https://img.magnific.com/free-vector/vegetables-realistic-composition-white-background-with-tomato-onion-sweet-hot-pepper-eggplant_1284-16242.jpg?semt=ais_hybrid&w=740&q=80',
                subLabel:'Vegetables'
            },
            {
                subIcon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ54QvFD5kgZRGV6n10nOKfdnj3uo6lx22k--qfcpy8Qg&s=10',
                subLabel:'Processed'
            },
        ]
    },
    {
        icon:'https://images.seattletimes.com/wp-content/uploads/2012/07/2018663715.jpg?d=780x0',
        label:'Apparels',
        subCategories:[
            {
                subIcon:'https://png.pngtree.com/png-clipart/20240527/original/pngtree-men-s-clothing-and-accessory-collection-on-hanger-png-image_15181971.png',
                subLabel:'Men'
            },
            {
                subIcon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR01t8hmhCkBT-_XxoRWnakfG9ugVVu4K8YA-0piOO8CROJfsItPpY9IPI&s=10',
                subLabel:'Women'
            },
            {
                subIcon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUXK1N-eRIihvseznPuR8LiOV7WudDC4fqQoYawOd0-b5RDkUmqZcD8bhz&s=10',
                subLabel:'Kids'
            },
            {
                subIcon:'https://static.vecteezy.com/system/resources/thumbnails/057/324/642/small/three-children-in-colorful-ethnic-clothing-free-png.png',
                subLabel:'Ethnic'
            },
        ]
    },
    {
        icon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStf5DMUa-DQYYsngGkzQetGtQpk1LJFRRo2pdXz_DTPA&s=10',
        label:'Cosmetics',
        subCategories:[
            {
                subIcon:'https://png.pngtree.com/png-vector/20230804/ourmid/pngtree-hair-care-vector-png-image_6892360.png',
                subLabel:'Hair'
            },
            {
                subIcon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB53-Y_bwD-yBugyOUbYky4QTzcT3y7z-zKDobd3tpUnOnTnM2G7D25Ms9&s=10',
                subLabel:'Skin'
            },
            {
                subIcon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3L7JXYDQLa0kwzJrHG0PGc7jUR25UtgenrioAuPTf3Q&s',
                subLabel:'Eyes'
            },
            {
                subIcon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRactVsgQMrL6mw2g-W0TlMa6IttYFaD_30JXIuhXB2OJC1tUKEHTfFAXfU&s=10',
                subLabel:'Nails'
            },
        ]
    },
    {
        icon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnyRPAH0sUIAG8vlUQml5R_oMXGxgQd_ep0wAmLv_qeQ&s=10',
        label:'Electronics',
        subCategories:[
            {
                subIcon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRQm5KaU1Jtr8fgPtFB5O5kyERvaCfWjwZSO1zxMB8rw&s=10',
                subLabel:'SmartPhones'
            },
            {
                subIcon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAjAkI7vk8hJ1y7iPNRAIDybOrPcSvqMRHCIRvSgXV3g&s=10',
                subLabel:'SmartWatches'
            },
            {
                subIcon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0yVpUxt5oWVRcd4LR1_KFxbTNqy2YFrODp5dinq6dBEMV697QY289I2E&s=10',
                subLabel:'Tablets'
            },
            {
                subIcon:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdrQO5GcVhuxTDZyjmVSGYwhILLv7cLDOaiUWiGTp7P0ibpX_Lm7eesy_B&s=10',
                subLabel:'Laptops'
            },
        ]
    },
]