export const categoryData = {
  "food": {
    "grains": [
      {
        "id": "GR001",
        "name": "Basmati Rice",
        "brand": "Daawat",
        "price": 799,
        "quantity": 5,
        "unit": "kg",
        "image": "https://w7.pngwing.com/pngs/596/447/png-transparent-rice-sagar-parajuli.png",
        "description": "Premium long-grain basmati rice with rich aroma.",
        "rating": 4.8,
        "reviews": 324,
        "discount": 12,
        "stock": 85
      },
      {
        "id": "GR002",
        "name": "Brown Rice",
        "brand": "India Gate",
        "price": 450,
        "quantity": 5,
        "unit": "kg",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHNiCneCQ8xAnOleB-VIS7LaKjIX_lPoLqtN64swFJ8Q&s=10",
        "description": "Healthy whole-grain brown rice rich in fiber.",
        "rating": 4.6,
        "reviews": 212,
        "discount": 10,
        "stock": 62
      },
      {
        "id": "GR003",
        "name": "Whole Wheat Flour",
        "brand": "Aashirvaad",
        "price": 315,
        "quantity": 5,
        "unit": "kg",
        "image": "https://png.pngtree.com/png-vector/20240904/ourmid/pngtree-wooden-bowl-with-brown-wheat-flour-atta-on-transparent-background-png-image_13746063.png",
        "description": "Fresh chakki atta for soft and fluffy rotis.",
        "rating": 4.9,
        "reviews": 845,
        "discount": 8,
        "stock": 110
      },
      {
        "id": "GR004",
        "name": "Rolled Oats",
        "brand": "Quaker",
        "price": 225,
        "quantity": 1,
        "unit": "kg",
        "image": "https://png.pngtree.com/png-clipart/20250103/original/pngtree-realistic-rolled-oats-clipart-for-recipe-and-culinary-illustrations-png-image_19530284.png",
        "description": "Nutritious rolled oats ideal for breakfast.",
        "rating": 4.7,
        "reviews": 467,
        "discount": 15,
        "stock": 58
      },
      {
        "id": "GR005",
        "name": "Foxtail Millet",
        "brand": "24 Mantra",
        "price": 180,
        "quantity": 1,
        "unit": "kg",
        "image": "https://icon2.cleanpng.com/lnd/20240911/ug/10edeae79acfb5c2371c8c145e7b55.webp",
        "description": "Organic foxtail millet packed with nutrients.",
        "rating": 4.5,
        "reviews": 173,
        "discount": 10,
        "stock": 46
      }
    ],
    "fruits": [
      {
        "id": "FR001",
        "name": "Apple",
        "brand": "Fresh Farm",
        "price": 180,
        "quantity": 1,
        "unit": "kg",
        "image": "https://png.pngtree.com/element_our/png/20181129/vector-illustration-of-fresh-red-apple-with-single-leaf-png_248312.jpg",
        "description": "Fresh and juicy Kashmiri apples rich in fiber and vitamins.",
        "rating": 4.8,
        "reviews": 542,
        "discount": 10,
        "stock": 65
      },
      {
        "id": "FR002",
        "name": "Banana",
        "brand": "Organic Fresh",
        "price": 60,
        "quantity": 1,
        "unit": "dozen",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIBbI2OLTgOQB0QAj00W_wfzXRc5gCaXFraHb0GTjjBJNiqdoTZ_aDBDg&s=10",
        "description": "Naturally sweet bananas packed with potassium and energy.",
        "rating": 4.7,
        "reviews": 423,
        "discount": 5,
        "stock": 120
      },
      {
        "id": "FR003",
        "name": "Orange",
        "brand": "Nagpur Fresh",
        "price": 90,
        "quantity": 1,
        "unit": "kg",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHh_qdALuUas_FSsGXUvuyqKBowIufFAGqovO1EnH9WVl_q78BXy6oBxk&s=10",
        "description": "Sweet and juicy oranges loaded with Vitamin C.",
        "rating": 4.6,
        "reviews": 351,
        "discount": 8,
        "stock": 70
      },
      {
        "id": "FR004",
        "name": "Mango",
        "brand": "Alphonso",
        "price": 280,
        "quantity": 1,
        "unit": "kg",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTVg-0ENsVZpW26_ge_vcwy29CSxOLZvOlozeBZyArnQ&s",
        "description": "Premium Alphonso mangoes with rich aroma and sweetness.",
        "rating": 4.9,
        "reviews": 689,
        "discount": 12,
        "stock": 45
      },
      {
        "id": "FR005",
        "name": "Pomegranate",
        "brand": "Fresh Valley",
        "price": 220,
        "quantity": 1,
        "unit": "kg",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJy3UYiGrYgCU435Kb2SYK4_paZKPhX4wtU40JmGLxtA&s=10",
        "description": "Fresh pomegranates full of antioxidants and nutrients.",
        "rating": 4.8,
        "reviews": 298,
        "discount": 9,
        "stock": 52
      },
    ],
    "vegetables": [
      {
        "id": "VEG001",
        "name": "Potato",
        "brand": "Fresh Farm",
        "price": 35,
        "quantity": 1,
        "unit": "kg",
        "image": "https://static.vecteezy.com/system/resources/thumbnails/048/050/936/small/potatoes-with-leaves-on-transparent-background-background-png.png",
        "description": "Farm fresh potatoes suitable for everyday cooking.",
        "rating": 4.6,
        "reviews": 482,
        "discount": 5,
        "stock": 150
      },
      {
        "id": "VEG002",
        "name": "Tomato",
        "brand": "Organic Fresh",
        "price": 40,
        "quantity": 1,
        "unit": "kg",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSX5pu3AU_G8e57Bfgf9zQDMLE9f1xe01ILnWr5GkdtQA&s=10",
        "description": "Juicy red tomatoes perfect for curries and salads.",
        "rating": 4.7,
        "reviews": 396,
        "discount": 8,
        "stock": 120
      },
      {
        "id": "VEG003",
        "name": "Onion",
        "brand": "Nature Fresh",
        "price": 38,
        "quantity": 1,
        "unit": "kg",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRdEqcspaIXBeKEvijviI-r9eBCvLlRQCXUjg1-Y42mg&s=10",
        "description": "Fresh onions with rich flavor and long shelf life.",
        "rating": 4.5,
        "reviews": 351,
        "discount": 6,
        "stock": 180
      },
      {
        "id": "VEG004",
        "name": "Carrot",
        "brand": "Farm Fresh",
        "price": 55,
        "quantity": 1,
        "unit": "kg",
        "image": "https://png.pngtree.com/png-vector/20241225/ourmid/pngtree-fresh-organic-carrots-in-a-neat-stack-png-image_14812590.png",
        "description": "Crunchy carrots rich in Vitamin A.",
        "rating": 4.8,
        "reviews": 245,
        "discount": 10,
        "stock": 90
      },
      {
        "id": "VEG005",
        "name": "Spinach",
        "brand": "Green Leaf",
        "price": 25,
        "quantity": 1,
        "unit": "bundle",
        "image": "https://png.pngtree.com/png-clipart/20231016/original/pngtree-fresh-spinach-vegetable-png-image_13322802.png",
        "description": "Fresh green spinach packed with iron and nutrients.",
        "rating": 4.6,
        "reviews": 178,
        "discount": 5,
        "stock": 70
      },
    ],
    "processed": [
      {
        "id": "PRO001",
        "name": "Marie Gold Biscuits",
        "brand": "Britannia",
        "price": 35,
        "quantity": 200,
        "unit": "gm",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZgqVRBKmlxpH3Tz4Y6GKYESscPiG19B_COiK8dCwAkQ&s=10",
        "description": "Light and crispy tea-time biscuits loved by all age groups.",
        "rating": 4.7,
        "reviews": 648,
        "discount": 5,
        "stock": 180
      },
      {
        "id": "PRO002",
        "name": "Chocolate Cake",
        "brand": "Monginis",
        "price": 450,
        "quantity": 1,
        "unit": "item",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAzavpbsN0WFlI4KEiAfkBftEMvE0jOc5akDQlQ9arbQ&s=10",
        "description": "Soft and delicious chocolate cake perfect for celebrations.",
        "rating": 4.9,
        "reviews": 395,
        "discount": 10,
        "stock": 28
      },
      {
        "id": "PRO003",
        "name": "Instant Noodles",
        "brand": "Maggi",
        "price": 70,
        "quantity": 280,
        "unit": "gm",
        "image": "https://static.vecteezy.com/system/resources/thumbnails/051/125/508/small/delicious-fried-noodles-isolated-on-transparent-background-png.png",
        "description": "Quick and tasty instant noodles ready in just 2 minutes.",
        "rating": 4.8,
        "reviews": 1452,
        "discount": 8,
        "stock": 250
      },
      {
        "id": "PRO004",
        "name": "Corn Flakes",
        "brand": "Kellogg's",
        "price": 215,
        "quantity": 475,
        "unit": "gm",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjRclEhUUShYihiu0VKcFAKH1dTAd2xqTLiWP6y89gjA&s=10",
        "description": "Crunchy breakfast cereal fortified with essential vitamins.",
        "rating": 4.6,
        "reviews": 521,
        "discount": 12,
        "stock": 84
      },
      {
        "id": "PRO005",
        "name": "Tomato Ketchup",
        "brand": "Kissan",
        "price": 120,
        "quantity": 500,
        "unit": "gm",
        "image": "https://pngimg.com/uploads/ketchup/ketchup_PNG23.png",
        "description": "Rich and tangy tomato ketchup made from fresh tomatoes.",
        "rating": 4.7,
        "reviews": 610,
        "discount": 10,
        "stock": 105
      }
    ]
  },
  "apparels": {
    "men": [
      {
        "id": "MEN001",
        "name": "Round Neck Cotton T-Shirt",
        "brand": "Puma",
        "category": "Apparels",
        "subCategory": "Men",
        "price": 799,
        "originalPrice": 999,
        "discount": 20,
        "rating": 4.6,
        "reviews": 324,
        "quantity": 1,
        "unit": "item",
        "stock": 52,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://5.imimg.com/data5/NR/KD/XN/SELLER-31619481/men-round-neck-t-shirt.jpeg",
        "description": "Soft 100% cotton round neck T-shirt suitable for casual wear."
      },
      {
        "id": "MEN002",
        "name": "Slim Fit Jeans",
        "brand": "Levi's",
        "category": "Apparels",
        "subCategory": "Men",
        "price": 2499,
        "originalPrice": 2999,
        "discount": 17,
        "rating": 4.8,
        "reviews": 512,
        "quantity": 1,
        "unit": "item",
        "stock": 34,
        "delivery": "2 Days",
        "isBestSeller": true,
        "image": "https://img.magnific.com/free-photo/jeans_1203-8094.jpg?semt=ais_hybrid&w=740&q=80",
        "description": "Comfortable slim-fit denim jeans for everyday wear."
      },
      {
        "id": "MEN003",
        "name": "Formal Shirt",
        "brand": "Arrow",
        "category": "Apparels",
        "subCategory": "Men",
        "price": 1899,
        "originalPrice": 2399,
        "discount": 21,
        "rating": 4.7,
        "reviews": 281,
        "quantity": 1,
        "unit": "item",
        "stock": 41,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsXk1YJvYqedpBJJlnKi5uT9dRZqfWPFGzchNKLyyTYg&s=10",
        "description": "Premium cotton formal shirt for office and business meetings."
      },
      {
        "id": "MEN004",
        "name": "Hooded Sweatshirt",
        "brand": "Nike",
        "category": "Apparels",
        "subCategory": "Men",
        "price": 2999,
        "originalPrice": 3499,
        "discount": 14,
        "rating": 4.8,
        "reviews": 467,
        "quantity": 1,
        "unit": "item",
        "stock": 29,
        "delivery": "2 Days",
        "isBestSeller": true,
        "image": "https://img.magnific.com/free-psd/blank-white-hoodie-mockup-back-view-perfect-design-presentation_191095-83416.jpg?semt=ais_hybrid&w=740&q=80",
        "description": "Warm fleece hoodie perfect for winter and casual outings."
      },
      {
        "id": "MEN005",
        "name": "Running Shoes",
        "brand": "Adidas",
        "category": "Apparels",
        "subCategory": "Men",
        "price": 4299,
        "originalPrice": 4999,
        "discount": 14,
        "rating": 4.9,
        "reviews": 728,
        "quantity": 1,
        "unit": "pair",
        "stock": 22,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://static.vecteezy.com/system/resources/thumbnails/049/949/365/small/a-pair-of-running-shoes-on-a-black-background-png.png",
        "description": "Lightweight running shoes with breathable mesh upper."
      }
    ],
    "women": [
      {
        "id": "WM001",
        "name": "Floral Printed Kurti",
        "brand": "Biba",
        "category": "Apparels",
        "subCategory": "Women",
        "price": 1499,
        "originalPrice": 1999,
        "discount": 25,
        "rating": 4.8,
        "reviews": 485,
        "quantity": 1,
        "unit": "item",
        "stock": 40,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgGhx-tBOZXyrj7pF1m8m2fn8Qw7ygbvEL6VsTzx-gC8uE4jJyMgr83EjO&s=10",
        "description": "Elegant floral cotton kurti suitable for casual and festive wear."
      },
      {
        "id": "WM002",
        "name": "Women's Denim Jeans",
        "brand": "Levi's",
        "category": "Apparels",
        "subCategory": "Women",
        "price": 2699,
        "originalPrice": 3199,
        "discount": 16,
        "rating": 4.7,
        "reviews": 364,
        "quantity": 1,
        "unit": "item",
        "stock": 31,
        "delivery": "2 Days",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv69HlmTSxmTRzNvpDb3DvIGnIVWnfxBdd9SK4EdmBbdpjTjGGeQZlpuI&s=10",
        "description": "Stretchable slim-fit denim jeans for everyday comfort."
      },
      {
        "id": "WM003",
        "name": "Cotton Saree",
        "brand": "FabIndia",
        "category": "Apparels",
        "subCategory": "Women",
        "price": 2199,
        "originalPrice": 2699,
        "discount": 19,
        "rating": 4.9,
        "reviews": 295,
        "quantity": 1,
        "unit": "item",
        "stock": 25,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTepaXXWvBslKnJXJlto9fZ-EYjLxnDuVCLf09bxCKrBg&s=10",
        "description": "Traditional cotton saree with elegant border design."
      },
      {
        "id": "WM004",
        "name": "Casual Top",
        "brand": "Zara",
        "category": "Apparels",
        "subCategory": "Women",
        "price": 1299,
        "originalPrice": 1599,
        "discount": 19,
        "rating": 4.6,
        "reviews": 212,
        "quantity": 1,
        "unit": "item",
        "stock": 38,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://5.imimg.com/data5/SELLER/Default/2023/7/325455372/SS/OM/DD/158819287/girls-printed-tops-500x500.png",
        "description": "Stylish casual top made with premium soft fabric."
      },
      {
        "id": "WM005",
        "name": "Sports Shoes",
        "brand": "Skechers",
        "category": "Apparels",
        "subCategory": "Women",
        "price": 3899,
        "originalPrice": 4499,
        "discount": 13,
        "rating": 4.8,
        "reviews": 417,
        "quantity": 1,
        "unit": "pair",
        "stock": 19,
        "delivery": "2 Days",
        "isBestSeller": true,
        "image": "https://toppng.com/uploads/preview/running-shoes-11530959070lnqqizvlq8.png",
        "description": "Comfortable walking and running shoes with memory foam."
      }
    ],
    "kids": [
      {
        "id": "KD001",
        "name": "Boys Graphic T-Shirt",
        "brand": "Max",
        "category": "Apparels",
        "subCategory": "Kids",
        "price": 499,
        "originalPrice": 699,
        "discount": 29,
        "rating": 4.7,
        "reviews": 168,
        "quantity": 1,
        "unit": "item",
        "stock": 64,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHsaHPFUCvWXcgK-8_SUfGCQn_ZAGFxaEyFdJcmitirw&s=10",
        "description": "Soft cotton graphic T-shirt for boys with comfortable fit."
      },
      {
        "id": "KD002",
        "name": "Girls Floral Frock",
        "brand": "Hopscotch",
        "category": "Apparels",
        "subCategory": "Kids",
        "price": 899,
        "originalPrice": 1199,
        "discount": 25,
        "rating": 4.8,
        "reviews": 214,
        "quantity": 1,
        "unit": "item",
        "stock": 42,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeZ5MOVJQlpOnICCbzOXc5h6zFZh41ROZbVyNH6FzMIzmQJup73dynGU8&s=10",
        "description": "Beautiful floral frock made from soft and breathable fabric."
      },
      {
        "id": "KD003",
        "name": "Kids Denim Shorts",
        "brand": "Pantaloons",
        "category": "Apparels",
        "subCategory": "Kids",
        "price": 649,
        "originalPrice": 849,
        "discount": 24,
        "rating": 4.6,
        "reviews": 132,
        "quantity": 1,
        "unit": "item",
        "stock": 50,
        "delivery": "2 Days",
        "isBestSeller": false,
        "image": "https://png.pngtree.com/png-vector/20250115/ourmid/pngtree-blue-denim-shorts-with-a-classic-fit-and-casual-style-png-image_15200034.png",
        "description": "Comfortable denim shorts suitable for daily wear."
      },
      {
        "id": "KD004",
        "name": "Kids Hoodie",
        "brand": "H&M",
        "category": "Apparels",
        "subCategory": "Kids",
        "price": 1299,
        "originalPrice": 1599,
        "discount": 19,
        "rating": 4.8,
        "reviews": 176,
        "quantity": 1,
        "unit": "item",
        "stock": 31,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQC7URIgG7u_MAA4-qk4rsc42dOHLa-lsz1pdEb_dYFYw&s=10",
        "description": "Warm hooded sweatshirt for kids with soft fleece lining."
      },
      {
        "id": "KD005",
        "name": "School Shoes",
        "brand": "Bata",
        "category": "Apparels",
        "subCategory": "Kids",
        "price": 999,
        "originalPrice": 1299,
        "discount": 23,
        "rating": 4.7,
        "reviews": 245,
        "quantity": 1,
        "unit": "pair",
        "stock": 39,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://static.vecteezy.com/system/resources/thumbnails/046/006/125/small/classic-black-leather-dress-shoes-free-png.png",
        "description": "Durable and lightweight black school shoes for children."
      }
    ],
    "ethnic": [
      {
        "id": "ET001",
        "name": "Men's Kurta Pajama Set",
        "brand": "Manyavar",
        "category": "Apparels",
        "subCategory": "Ethnic",
        "price": 2999,
        "originalPrice": 3599,
        "discount": 17,
        "rating": 4.8,
        "reviews": 348,
        "quantity": 1,
        "unit": "item",
        "stock": 28,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://png.pngtree.com/png-clipart/20250115/original/pngtree-green-kurta-outfit-for-men-png-image_20002767.png",
        "description": "Elegant cotton kurta pajama set for festive occasions."
      },
      {
        "id": "ET002",
        "name": "Women's Designer Lehenga",
        "brand": "Libas",
        "category": "Apparels",
        "subCategory": "Ethnic",
        "price": 6499,
        "originalPrice": 7999,
        "discount": 19,
        "rating": 4.9,
        "reviews": 276,
        "quantity": 1,
        "unit": "item",
        "stock": 18,
        "delivery": "2 Days",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc85RNS-md2BMXgJ-jLejror2B_PiqWSzSCb1f2LQgV0tVuw3Pi0dkSbr0&s=10",
        "description": "Beautiful embroidered lehenga perfect for weddings and festivals."
      },
      {
        "id": "ET003",
        "name": "Silk Saree",
        "brand": "Kalanjali",
        "category": "Apparels",
        "subCategory": "Ethnic",
        "price": 5499,
        "originalPrice": 6499,
        "discount": 15,
        "rating": 4.8,
        "reviews": 198,
        "quantity": 1,
        "unit": "item",
        "stock": 22,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://static.vecteezy.com/system/resources/thumbnails/057/227/293/small/beautiful-indian-woman-in-red-sari-free-png.png",
        "description": "Premium silk saree with elegant traditional weaving."
      },
      {
        "id": "ET004",
        "name": "Nehru Jacket",
        "brand": "Raymond",
        "category": "Apparels",
        "subCategory": "Ethnic",
        "price": 2499,
        "originalPrice": 2999,
        "discount": 17,
        "rating": 4.7,
        "reviews": 167,
        "quantity": 1,
        "unit": "item",
        "stock": 33,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLoFvRU3waXx5ygDj-DSJrF-GzD1JQZZWXZ8AREZeIlQ&s=10",
        "description": "Classic Nehru jacket for festive and formal ethnic wear."
      },
      {
        "id": "ET005",
        "name": "Embroidered Dupatta",
        "brand": "W for Woman",
        "category": "Apparels",
        "subCategory": "Ethnic",
        "price": 1199,
        "originalPrice": 1499,
        "discount": 20,
        "rating": 4.6,
        "reviews": 142,
        "quantity": 1,
        "unit": "item",
        "stock": 45,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmzWr4PTngQp2ADiKhtiuYsHyfuThlYAL5tqumlbSxqw&s=10",
        "description": "Elegant embroidered dupatta crafted with premium fabric."
      }
    ]
  },
  "cosmetics": {
    "hair": [
      {
        "id": "HR001",
        "name": "Anti Hair Fall Shampoo",
        "brand": "L'Oréal Paris",
        "category": "Cosmetics",
        "subCategory": "Hair",
        "price": 399,
        "originalPrice": 499,
        "discount": 20,
        "rating": 4.7,
        "reviews": 864,
        "quantity": 340,
        "unit": "ml",
        "stock": 62,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSPK55qMvzBJR06nSWCsgsPjdAWP9lOdb_izdM2MYlfdAzIaS7gZ9PaF4&s=10",
        "description": "Strengthens hair roots and helps reduce hair fall."
      },
      {
        "id": "HR002",
        "name": "Coconut Hair Oil",
        "brand": "Parachute",
        "category": "Cosmetics",
        "subCategory": "Hair",
        "price": 210,
        "originalPrice": 240,
        "discount": 13,
        "rating": 4.8,
        "reviews": 1245,
        "quantity": 500,
        "unit": "ml",
        "stock": 104,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_8pfsSicEr3PFWkzDMjMo0uzd8fB7uQT78fa4J5NEHg&s=10",
        "description": "100% pure coconut hair oil for healthy and shiny hair."
      },
      {
        "id": "HR003",
        "name": "Hair Conditioner",
        "brand": "Dove",
        "category": "Cosmetics",
        "subCategory": "Hair",
        "price": 325,
        "originalPrice": 399,
        "discount": 19,
        "rating": 4.6,
        "reviews": 532,
        "quantity": 340,
        "unit": "ml",
        "stock": 48,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQW42Eq0bVQuyD5_AeClv4ZvtHe9CTEGh7_FvWAh_n9w&s=10",
        "description": "Smoothens dry hair and provides deep nourishment."
      },
      {
        "id": "HR004",
        "name": "Hair Serum",
        "brand": "Streax",
        "category": "Cosmetics",
        "subCategory": "Hair",
        "price": 275,
        "originalPrice": 349,
        "discount": 21,
        "rating": 4.7,
        "reviews": 418,
        "quantity": 100,
        "unit": "ml",
        "stock": 56,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2X5BQn8G5sWj2qREUsoQlbRPXdvTBJ_MemcrN1X8Pcg&s=10",
        "description": "Adds shine, controls frizz, and protects hair."
      },
      {
        "id": "HR005",
        "name": "Onion Hair Mask",
        "brand": "Mamaearth",
        "category": "Cosmetics",
        "subCategory": "Hair",
        "price": 549,
        "originalPrice": 649,
        "discount": 15,
        "rating": 4.8,
        "reviews": 389,
        "quantity": 200,
        "unit": "gm",
        "stock": 37,
        "delivery": "2 Days",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmiEzyaVaWiIAdgLJfYTt5t_F3QkFOWZGnS7-Np3VaHtqPJ52_qI6HNKrn&s=10",
        "description": "Hair mask enriched with onion oil for stronger hair."
      }
    ],
    "skin": [
      {
        "id": "SK001",
        "name": "Vitamin C Face Wash",
        "brand": "Mamaearth",
        "category": "Cosmetics",
        "subCategory": "Skin",
        "price": 299,
        "originalPrice": 349,
        "discount": 14,
        "rating": 4.8,
        "reviews": 973,
        "quantity": 100,
        "unit": "ml",
        "stock": 71,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA5FEvCdZPowi38hENY6M9ZQte-SLttRUNy8nT4JUVEkLX6HAqlIzpPUfF&s=10",
        "description": "Gentle face wash that brightens and refreshes skin."
      },
      {
        "id": "SK002",
        "name": "Daily Moisturizing Cream",
        "brand": "Nivea",
        "category": "Cosmetics",
        "subCategory": "Skin",
        "price": 285,
        "originalPrice": 325,
        "discount": 12,
        "rating": 4.7,
        "reviews": 842,
        "quantity": 200,
        "unit": "ml",
        "stock": 64,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://png.pngtree.com/png-vector/20230426/ourmid/pngtree-skin-care-transparent-face-cream-png-image_6728185.png",
        "description": "Provides long-lasting hydration for soft skin."
      },
      {
        "id": "SK003",
        "name": "SPF 50 Sunscreen",
        "brand": "Minimalist",
        "category": "Cosmetics",
        "subCategory": "Skin",
        "price": 499,
        "originalPrice": 599,
        "discount": 17,
        "rating": 4.9,
        "reviews": 612,
        "quantity": 50,
        "unit": "gm",
        "stock": 46,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://png.pngtree.com/png-clipart/20210522/ourmid/pngtree-sunscreen-cream-spf-50-png-image_3340258.jpg",
        "description": "Broad-spectrum sunscreen with SPF 50 PA++++ protection."
      },
      {
        "id": "SK004",
        "name": "Aloe Vera Gel",
        "brand": "Patanjali",
        "category": "Cosmetics",
        "subCategory": "Skin",
        "price": 199,
        "originalPrice": 249,
        "discount": 20,
        "rating": 4.6,
        "reviews": 531,
        "quantity": 150,
        "unit": "gm",
        "stock": 83,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://png.pngtree.com/png-clipart/20250108/original/pngtree-fresh-aloe-vera-gel-with-soothing-properties-nature-s-solution-for-png-image_18954154.png",
        "description": "Pure aloe vera gel for soothing and moisturizing skin."
      },
      {
        "id": "SK005",
        "name": "Charcoal Face Scrub",
        "brand": "WOW Skin Science",
        "category": "Cosmetics",
        "subCategory": "Skin",
        "price": 349,
        "originalPrice": 449,
        "discount": 22,
        "rating": 4.7,
        "reviews": 427,
        "quantity": 100,
        "unit": "gm",
        "stock": 54,
        "delivery": "2 Days",
        "isBestSeller": false,
        "image": "https://rukminim2.flixcart.com/image/480/640/xif0q/scrub/x/q/q/100-charcoal-face-scrub-with-lemongrass-eucalyptus-essential-enriched-transparent-original-imagtmuaj5xh9zsv.png?q=20",
        "description": "Deep cleansing charcoal scrub that removes dead skin cells."
      }
    ],
    "eyes": [
      {
        "id": "EY001",
        "name": "Colossal Kajal",
        "brand": "Maybelline",
        "category": "Cosmetics",
        "subCategory": "Eyes",
        "price": 199,
        "originalPrice": 249,
        "discount": 20,
        "rating": 4.8,
        "reviews": 1842,
        "quantity": 1,
        "unit": "item",
        "stock": 95,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://aapkabazar.co/_next/image?url=https%3A%2F%2Fimage.aapkabazar.co%2Fproduct%2F1630%2F1741415472955.png%3Ftype%3Dwebp%26width%3D600&w=3840&q=75",
        "description": "Smudge-proof kajal with intense black color lasting up to 24 hours."
      },
      {
        "id": "EY002",
        "name": "Waterproof Mascara",
        "brand": "Lakmé",
        "category": "Cosmetics",
        "subCategory": "Eyes",
        "price": 399,
        "originalPrice": 499,
        "discount": 20,
        "rating": 4.7,
        "reviews": 967,
        "quantity": 9,
        "unit": "ml",
        "stock": 58,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://png.pngtree.com/png-vector/20240723/ourmid/pngtree-lancome-monsieur-big-mascara-waterproof-black-png-image_13223804.png",
        "description": "Long-lasting waterproof mascara for fuller-looking lashes."
      },
      {
        "id": "EY003",
        "name": "Liquid Eyeliner",
        "brand": "L'Oréal Paris",
        "category": "Cosmetics",
        "subCategory": "Eyes",
        "price": 499,
        "originalPrice": 599,
        "discount": 17,
        "rating": 4.8,
        "reviews": 643,
        "quantity": 6,
        "unit": "ml",
        "stock": 46,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://static.vecteezy.com/system/resources/thumbnails/073/173/016/small/eyeliner-icon-3d-render-illustration-png.png",
        "description": "Precision-tip liquid eyeliner with deep matte finish."
      },
      {
        "id": "EY004",
        "name": "Eyeshadow Palette",
        "brand": "Swiss Beauty",
        "category": "Cosmetics",
        "subCategory": "Eyes",
        "price": 699,
        "originalPrice": 899,
        "discount": 22,
        "rating": 4.9,
        "reviews": 584,
        "quantity": 18,
        "unit": "gm",
        "stock": 32,
        "delivery": "2 Days",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3-yjDAsQv_Caijfy4RYri_2uUBfYxF3e9hQ8NaojXjuDj1rL0r6LehUDR&s=10",
        "description": "18-shade eyeshadow palette with matte and shimmer colors."
      },
      {
        "id": "EY005",
        "name": "Eyebrow Pencil",
        "brand": "Faces Canada",
        "category": "Cosmetics",
        "subCategory": "Eyes",
        "price": 249,
        "originalPrice": 299,
        "discount": 17,
        "rating": 4.6,
        "reviews": 318,
        "quantity": 1,
        "unit": "item",
        "stock": 71,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWvnK4c2hChpx75-2GrxPZxCZfSQmEMU-vlghG863lUQ&s=10",
        "description": "Easy-to-use eyebrow pencil for naturally defined brows."
      }
    ],
    "nails": [
      {
        "id": "NL001",
        "name": "Long Wear Nail Polish",
        "brand": "Lakmé",
        "category": "Cosmetics",
        "subCategory": "Nails",
        "price": 199,
        "originalPrice": 249,
        "discount": 20,
        "rating": 4.7,
        "reviews": 825,
        "quantity": 10,
        "unit": "ml",
        "stock": 92,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPn6lZvBWnT00OovQOZGDHH30amuLSSEUL1nmHlEnfqQ&s=10",
        "description": "Glossy long-lasting nail polish with vibrant color."
      },
      {
        "id": "NL002",
        "name": "Nail Polish Remover",
        "brand": "Colorbar",
        "category": "Cosmetics",
        "subCategory": "Nails",
        "price": 175,
        "originalPrice": 220,
        "discount": 20,
        "rating": 4.6,
        "reviews": 467,
        "quantity": 110,
        "unit": "ml",
        "stock": 63,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLDkA1GO2w19xRh5OqnqQxxXuUblbdkf4lYUp3LWkzYy4UDWYNwr_YCNc&s=10",
        "description": "Acetone-free nail polish remover enriched with Vitamin E."
      },
      {
        "id": "NL003",
        "name": "Base Coat",
        "brand": "Nykaa",
        "category": "Cosmetics",
        "subCategory": "Nails",
        "price": 299,
        "originalPrice": 349,
        "discount": 14,
        "rating": 4.7,
        "reviews": 354,
        "quantity": 12,
        "unit": "ml",
        "stock": 48,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://images-static.nykaa.com/media/catalog/product/5/d/5d90ba78908003747521_2.png?tr=w-500",
        "description": "Protective base coat that improves nail polish durability."
      },
      {
        "id": "NL004",
        "name": "Top Coat Gel Finish",
        "brand": "Faces Canada",
        "category": "Cosmetics",
        "subCategory": "Nails",
        "price": 349,
        "originalPrice": 399,
        "discount": 13,
        "rating": 4.8,
        "reviews": 298,
        "quantity": 12,
        "unit": "ml",
        "stock": 41,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://www.favaigel.com/cdn/shop/files/IMG-7518_6488224e-6379-405a-a54f-08661f35920b_1200x1200.png?v=1771380908",
        "description": "High-shine gel finish top coat for salon-like nails."
      },
      {
        "id": "NL005",
        "name": "Professional Nail File Set",
        "brand": "Vega",
        "category": "Cosmetics",
        "subCategory": "Nails",
        "price": 149,
        "originalPrice": 199,
        "discount": 25,
        "rating": 4.5,
        "reviews": 276,
        "quantity": 1,
        "unit": "set",
        "stock": 74,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLFcGadYatlHV_D57GUgOpcA0LkWqH-GVUYIHJbDEMfw&s=10",
        "description": "Professional nail file set for shaping and smoothing nails."
      }
    ]
  },
  "electronics": {
    "smartphones": [
      {
        "id": "SP001",
        "name": "Samsung Galaxy S25",
        "brand": "Samsung",
        "category": "Electronics",
        "subCategory": "Smartphones",
        "price": 79999,
        "originalPrice": 85999,
        "discount": 7,
        "rating": 4.9,
        "reviews": 2541,
        "quantity": 1,
        "unit": "item",
        "stock": 32,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR72RD24cSznp4vaZWHjtLrYULCc23ykYKWTXIJM3tz6A&s=10",
        "description": "Flagship smartphone featuring Galaxy AI, AMOLED display, and an advanced camera system."
      },
      {
        "id": "SP002",
        "name": "Apple iPhone 16",
        "brand": "Apple",
        "category": "Electronics",
        "subCategory": "Smartphones",
        "price": 84900,
        "originalPrice": 89900,
        "discount": 6,
        "rating": 4.9,
        "reviews": 3826,
        "quantity": 1,
        "unit": "item",
        "stock": 28,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://pngimg.com/uploads/iphone16/iphone16_PNG38.png",
        "description": "Powerful iPhone with A18 chip, excellent cameras, and long battery life."
      },
      {
        "id": "SP003",
        "name": "OnePlus 13",
        "brand": "OnePlus",
        "category": "Electronics",
        "subCategory": "Smartphones",
        "price": 69999,
        "originalPrice": 74999,
        "discount": 7,
        "rating": 4.8,
        "reviews": 1845,
        "quantity": 1,
        "unit": "item",
        "stock": 41,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTnb7kIUfptlkMlvSjzfzINwwX25UAvQamh0l23xJw6A&s",
        "description": "Premium flagship phone with Snapdragon processor and ultra-fast charging."
      },
      {
        "id": "SP004",
        "name": "Google Pixel 9 Pro",
        "brand": "Google",
        "category": "Electronics",
        "subCategory": "Smartphones",
        "price": 92999,
        "originalPrice": 99999,
        "discount": 7,
        "rating": 4.8,
        "reviews": 1264,
        "quantity": 1,
        "unit": "item",
        "stock": 19,
        "delivery": "2 Days",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlUfq5boOzKC4rOHmMnhonAn-4Y7xDPn0_5eYMG3-rtQ&s=10",
        "description": "AI-powered smartphone with industry-leading camera and pure Android experience."
      },
      {
        "id": "SP005",
        "name": "Xiaomi 15",
        "brand": "Xiaomi",
        "category": "Electronics",
        "subCategory": "Smartphones",
        "price": 54999,
        "originalPrice": 59999,
        "discount": 8,
        "rating": 4.7,
        "reviews": 987,
        "quantity": 1,
        "unit": "item",
        "stock": 53,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr0q_e1bb-_x7MWd-Th66yv5wm4F5evXfpT7bv0iTlpA&s=10",
        "description": "High-performance smartphone with Leica camera technology and fast charging."
      }
    ],
    "smartwatches": [
      {
        "id": "SW001",
        "name": "Apple Watch Series 10",
        "brand": "Apple",
        "category": "Electronics",
        "subCategory": "Smartwatches",
        "price": 46900,
        "originalPrice": 49900,
        "discount": 6,
        "rating": 4.9,
        "reviews": 1624,
        "quantity": 1,
        "unit": "item",
        "stock": 18,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://media-ik.croma.com/Croma%20Assets/Communication/Wearable%20Devices/Images/309449_0_fias9q.png",
        "description": "Premium smartwatch with ECG, fitness tracking, and seamless iPhone integration."
      },
      {
        "id": "SW002",
        "name": "Samsung Galaxy Watch Ultra",
        "brand": "Samsung",
        "category": "Electronics",
        "subCategory": "Smartwatches",
        "price": 59999,
        "originalPrice": 64999,
        "discount": 8,
        "rating": 4.8,
        "reviews": 923,
        "quantity": 1,
        "unit": "item",
        "stock": 22,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://www.sathya.store/img/product/BJl5EGuusSw6IWV7.png",
        "description": "Premium smartwatch with advanced health tracking and rugged design."
      },
      {
        "id": "SW003",
        "name": "Noise ColorFit Pro 6",
        "brand": "Noise",
        "category": "Electronics",
        "subCategory": "Smartwatches",
        "price": 4999,
        "originalPrice": 5999,
        "discount": 17,
        "rating": 4.6,
        "reviews": 2156,
        "quantity": 1,
        "unit": "item",
        "stock": 74,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://www.gonoise.com/cdn/shop/files/Artboard_26_pro6max.webp?v=1763618903",
        "description": "Affordable smartwatch with AMOLED display, Bluetooth calling, and health tracking."
      },
      {
        "id": "SW004",
        "name": "boAt Lunar Pro LTE",
        "brand": "boAt",
        "category": "Electronics",
        "subCategory": "Smartwatches",
        "price": 9999,
        "originalPrice": 11999,
        "discount": 17,
        "rating": 4.5,
        "reviews": 1184,
        "quantity": 1,
        "unit": "item",
        "stock": 45,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://prod4-sprcdn-assets.sprinklr.com/200052/d8a567c4-a756-4b85-81eb-ace91f33feac-580111030/Lunar_Pro_LTE-removebg-preview.png",
        "description": "Feature-packed smartwatch with LTE connectivity and AMOLED display."
      },
      {
        "id": "SW005",
        "name": "Amazfit GTR 4",
        "brand": "Amazfit",
        "category": "Electronics",
        "subCategory": "Smartwatches",
        "price": 16999,
        "originalPrice": 18999,
        "discount": 11,
        "rating": 4.7,
        "reviews": 742,
        "quantity": 1,
        "unit": "item",
        "stock": 29,
        "delivery": "2 Days",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR29iZ6aZ7iA-FBM7s9RDdPLgBb4e62Q57R3YQxR_Oleg&s=10",
        "description": "Premium fitness smartwatch with GPS, long battery life, and over 150 sports modes."
      }
    ],
    "tablets": [
      {
        "id": "TB001",
        "name": "Apple iPad Air M3",
        "brand": "Apple",
        "category": "Electronics",
        "subCategory": "Tablets",
        "price": 59900,
        "originalPrice": 64900,
        "discount": 8,
        "rating": 4.9,
        "reviews": 1428,
        "quantity": 1,
        "unit": "item",
        "stock": 24,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://media-ik.croma.com/Croma%20Assets/Computers%20Peripherals/Tablets%20and%20iPads/Images/314205_0_iprcih.png",
        "description": "Powerful iPad Air with Apple M3 chip, Liquid Retina display, and Apple Pencil support."
      },
      {
        "id": "TB002",
        "name": "Samsung Galaxy Tab S10",
        "brand": "Samsung",
        "category": "Electronics",
        "subCategory": "Tablets",
        "price": 68999,
        "originalPrice": 73999,
        "discount": 7,
        "rating": 4.8,
        "reviews": 936,
        "quantity": 1,
        "unit": "item",
        "stock": 19,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXFFa_PRJxonQgFdcb8AhmStdsZ-DhCgJ0Ta1HTpxSpfw-Mjmi5fv6lc7t&s=10",
        "description": "Premium Android tablet with AMOLED display and S Pen included."
      },
      {
        "id": "TB003",
        "name": "OnePlus Pad 2",
        "brand": "OnePlus",
        "category": "Electronics",
        "subCategory": "Tablets",
        "price": 39999,
        "originalPrice": 44999,
        "discount": 11,
        "rating": 4.7,
        "reviews": 618,
        "quantity": 1,
        "unit": "item",
        "stock": 31,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://www.oneplus.com/content/dam/oasis/page/2024/global/product/rainbow/specgrey.png",
        "description": "High-performance tablet with a smooth 144Hz display and long battery life."
      },
      {
        "id": "TB004",
        "name": "Xiaomi Pad 7",
        "brand": "Xiaomi",
        "category": "Electronics",
        "subCategory": "Tablets",
        "price": 32999,
        "originalPrice": 35999,
        "discount": 8,
        "rating": 4.6,
        "reviews": 512,
        "quantity": 1,
        "unit": "item",
        "stock": 42,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMJkPqEatJL_mpiNk1JgychTLLqMntp9UwH7cN3XR4cw&s=10",
        "description": "Entertainment-focused tablet with Dolby Vision display and quad speakers."
      },
      {
        "id": "TB005",
        "name": "Lenovo Tab P12",
        "brand": "Lenovo",
        "category": "Electronics",
        "subCategory": "Tablets",
        "price": 28999,
        "originalPrice": 31999,
        "discount": 9,
        "rating": 4.6,
        "reviews": 431,
        "quantity": 1,
        "unit": "item",
        "stock": 38,
        "delivery": "2 Days",
        "isBestSeller": false,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8EVLg4YWYY6gKj9dhEyp30yvze8YYyf-xjhvfMG68bw&s=10",
        "description": "Versatile Android tablet ideal for work, entertainment, and online learning."
      }
    ],
    "laptops": [
      {
        "id": "LP001",
        "name": "MacBook Air M4",
        "brand": "Apple",
        "category": "Electronics",
        "subCategory": "Laptops",
        "price": 114900,
        "originalPrice": 119900,
        "discount": 4,
        "rating": 4.9,
        "reviews": 2318,
        "quantity": 1,
        "unit": "item",
        "stock": 15,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFNEReAqAAQGqYPx-ouIpeMo7d1sEJ1vMXFNSt6CB6-g&s=10",
        "description": "Ultra-thin laptop powered by Apple's M4 chip with exceptional battery life."
      },
      {
        "id": "LP002",
        "name": "Dell XPS 14",
        "brand": "Dell",
        "category": "Electronics",
        "subCategory": "Laptops",
        "price": 149999,
        "originalPrice": 159999,
        "discount": 6,
        "rating": 4.8,
        "reviews": 984,
        "quantity": 1,
        "unit": "item",
        "stock": 12,
        "delivery": "2 Days",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDdm2dOrnEzLunmSyl3FoddrZSR-hTduhdIPKyK9KRTQ&s=10",
        "description": "Premium Windows laptop featuring Intel Core Ultra processor and OLED display."
      },
      {
        "id": "LP003",
        "name": "HP Pavilion 15",
        "brand": "HP",
        "category": "Electronics",
        "subCategory": "Laptops",
        "price": 68999,
        "originalPrice": 74999,
        "discount": 8,
        "rating": 4.7,
        "reviews": 1267,
        "quantity": 1,
        "unit": "item",
        "stock": 26,
        "delivery": "Tomorrow",
        "isBestSeller": true,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg9IcIvgWviLSrnz8ck6Ue8EUMdzWJy1trGJVL_47RZi9k9VEQb9H3gjs&s=10",
        "description": "Reliable everyday laptop suitable for students and professionals."
      },
      {
        "id": "LP004",
        "name": "Lenovo ThinkPad E16",
        "brand": "Lenovo",
        "category": "Electronics",
        "subCategory": "Laptops",
        "price": 82999,
        "originalPrice": 89999,
        "discount": 8,
        "rating": 4.8,
        "reviews": 753,
        "quantity": 1,
        "unit": "item",
        "stock": 18,
        "delivery": "Tomorrow",
        "isBestSeller": false,
        "image": "https://p1-ofp.static.pub//fes/cms/2024/03/07/zpuzenaiwgirevtfhwakefypg46ff5766229.jpg",
        "description": "Business laptop with durable build, excellent keyboard, and long battery life."
      },
      {
        "id": "LP005",
        "name": "ASUS ROG Zephyrus G16",
        "brand": "ASUS",
        "category": "Electronics",
        "subCategory": "Laptops",
        "price": 169999,
        "originalPrice": 179999,
        "discount": 6,
        "rating": 4.9,
        "reviews": 645,
        "quantity": 1,
        "unit": "item",
        "stock": 9,
        "delivery": "2 Days",
        "isBestSeller": true,
        "image": "https://dlcdnwebimgs.asus.com/gain/ECB739CB-4E3F-4B1E-89DF-A17A9D75E2DD",
        "description": "High-performance gaming laptop with RTX graphics and premium OLED display."
      }
    ]
  }
}